apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: py-apirule
spec:
  gateway: kyma-system/kyma-gateway
  host: py-apirule.<hostname> # replace <hostname> with your Kyma hostname
  service:
    name: ourservice
    port: 80
  rules:
  - path: /.*
    methods: ["GET"]
    mutators: []
    accessStrategies:
    - handler: allow
      config: {}
